import React from 'react'
import './index.css'
import Nav from './navbar';


function PrivacyPolicy () {
  return (
    <div className='PrivacyPolicy'>
      <Nav />
      <div className='policy-container'>
        <h1>Privacy Policy</h1>
        <p>Last updated: October 01, 2024</p>
        <p>
          This Privacy Policy describes Our policies and procedures on the
          collection, use, and disclosure of Your information when You use the
          Service and tells You about Your privacy rights and how the law
          protects You.
        </p>
        <p>
          We use Your Personal data to provide and improve the Service. By using
          the Service, You agree to the collection and use of information in
          accordance with this Privacy Policy. This Privacy Policy has been
          created with the help of the{' '}
          <a
            href='https://www.freeprivacypolicy.com/free-privacy-policy-generator/'
            target='_blank' rel="noreferrer"
          >
            Free Privacy Policy Generator
          </a>
          .
        </p>

        <h2>Interpretation and Definitions</h2>

        <h3>Interpretation</h3>
        <p>
          The words of which the initial letter is capitalized have meanings
          defined under the following conditions. The following definitions
          shall have the same meaning regardless of whether they appear in
          singular or in plural.
        </p>

        <h3>Definitions</h3>
        <p>For the purposes of this Privacy Policy:</p>
        <ul>
          <li>
            <strong>Account</strong> means a unique account created for You to
            access our Service or parts of our Service.
          </li>
          <li>
            <strong>Affiliate</strong> means an entity that controls, is
            controlled by, or is under common control with a party, where
            "control" means ownership of 50% or more of the shares, equity
            interest, or other securities entitled to vote for election of
            directors or other managing authority.
          </li>
          <li>
            <strong>Company</strong> (referred to as either "the Company", "We",
            "Us" or "Our" in this Agreement) refers to Toggl, Dharma Hight.
          </li>
          <li>
            <strong>Cookies</strong> are small files that are placed on Your
            computer, mobile device, or any other device by a website,
            containing the details of Your browsing history on that website
            among its many uses.
          </li>
          <li>
            <strong>Country</strong> refers to: Maharashtra, India.
          </li>
          <li>
            <strong>Device</strong> means any device that can access the
            Service, such as a computer, a cellphone, or a digital tablet.
          </li>
          <li>
            <strong>Personal Data</strong> is any information that relates to an
            identified or identifiable individual.
          </li>
          <li>
            <strong>Service</strong> refers to the Website.
          </li>
          <li>
            <strong>Service Provider</strong> means any natural or legal person
            who processes the data on behalf of the Company. It refers to
            third-party companies or individuals employed by the Company to
            facilitate the Service, to provide the Service on behalf of the
            Company, to perform services related to the Service, or to assist
            the Company in analyzing how the Service is used.
          </li>
          <li>
            <strong>Third-party Social Media Service</strong> refers to any
            website or any social network website through which a User can log
            in or create an account to use the Service.
          </li>
          <li>
            <strong>Usage Data</strong> refers to data collected automatically,
            either generated by the use of the Service or from the Service
            infrastructure itself (for example, the duration of a page visit).
          </li>
          <li>
            <strong>Website</strong> refers to Toggl, accessible from{' '}
            <a
              href='toggl.app'
              rel='external nofollow noopener'
              target='_blank'
            >
              toggl.app
            </a>
            .
          </li>
          <li>
            <strong>You</strong> means the individual accessing or using the
            Service, or the company, or other legal entity on behalf of which
            such individual is accessing or using the Service, as applicable.
          </li>
        </ul>
      </div>
    </div>
  )
}

export default PrivacyPolicy
